//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;

var ttypes = require('./subsetter_types');
//HELPER FUNCTIONS AND STRUCTURES

fontSubsetter.SubsetterService_genSubset_args = function(args) {
  this.filePath = null;
  this.outputDir = null;
  this.subset = null;
  this.types = null;
  if (args) {
    if (args.filePath !== undefined) {
      this.filePath = args.filePath;
    }
    if (args.outputDir !== undefined) {
      this.outputDir = args.outputDir;
    }
    if (args.subset !== undefined) {
      this.subset = args.subset;
    }
    if (args.types !== undefined) {
      this.types = args.types;
    }
  }
};
fontSubsetter.SubsetterService_genSubset_args.prototype = {};
fontSubsetter.SubsetterService_genSubset_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.filePath = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.outputDir = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.subset = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.LIST) {
        var _size0 = 0;
        var _rtmp34;
        this.types = [];
        var _etype3 = 0;
        _rtmp34 = input.readListBegin();
        _etype3 = _rtmp34.etype;
        _size0 = _rtmp34.size;
        for (var _i5 = 0; _i5 < _size0; ++_i5)
        {
          var elem6 = null;
          elem6 = input.readI32();
          this.types.push(elem6);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

fontSubsetter.SubsetterService_genSubset_args.prototype.write = function(output) {
  output.writeStructBegin('SubsetterService_genSubset_args');
  if (this.filePath !== null && this.filePath !== undefined) {
    output.writeFieldBegin('filePath', Thrift.Type.STRING, 1);
    output.writeString(this.filePath);
    output.writeFieldEnd();
  }
  if (this.outputDir !== null && this.outputDir !== undefined) {
    output.writeFieldBegin('outputDir', Thrift.Type.STRING, 2);
    output.writeString(this.outputDir);
    output.writeFieldEnd();
  }
  if (this.subset !== null && this.subset !== undefined) {
    output.writeFieldBegin('subset', Thrift.Type.STRING, 3);
    output.writeString(this.subset);
    output.writeFieldEnd();
  }
  if (this.types !== null && this.types !== undefined) {
    output.writeFieldBegin('types', Thrift.Type.LIST, 4);
    output.writeListBegin(Thrift.Type.I32, this.types.length);
    for (var iter7 in this.types)
    {
      if (this.types.hasOwnProperty(iter7))
      {
        iter7 = this.types[iter7];
        output.writeI32(iter7);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

fontSubsetter.SubsetterService_genSubset_result = function(args) {
  this.ex = null;
  if (args instanceof ttypes.IOException) {
    this.ex = args;
    return;
  }
  if (args) {
    if (args.ex !== undefined) {
      this.ex = args.ex;
    }
  }
};
fontSubsetter.SubsetterService_genSubset_result.prototype = {};
fontSubsetter.SubsetterService_genSubset_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.ex = new ttypes.IOException();
        this.ex.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

fontSubsetter.SubsetterService_genSubset_result.prototype.write = function(output) {
  output.writeStructBegin('SubsetterService_genSubset_result');
  if (this.ex !== null && this.ex !== undefined) {
    output.writeFieldBegin('ex', Thrift.Type.STRUCT, 1);
    this.ex.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

fontSubsetter.SubsetterService_getFontInfo_args = function(args) {
  this.filePath = null;
  if (args) {
    if (args.filePath !== undefined) {
      this.filePath = args.filePath;
    }
  }
};
fontSubsetter.SubsetterService_getFontInfo_args.prototype = {};
fontSubsetter.SubsetterService_getFontInfo_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.filePath = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

fontSubsetter.SubsetterService_getFontInfo_args.prototype.write = function(output) {
  output.writeStructBegin('SubsetterService_getFontInfo_args');
  if (this.filePath !== null && this.filePath !== undefined) {
    output.writeFieldBegin('filePath', Thrift.Type.STRING, 1);
    output.writeString(this.filePath);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

fontSubsetter.SubsetterService_getFontInfo_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
fontSubsetter.SubsetterService_getFontInfo_result.prototype = {};
fontSubsetter.SubsetterService_getFontInfo_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.MAP) {
        var _size8 = 0;
        var _rtmp312;
        this.success = {};
        var _ktype9 = 0;
        var _vtype10 = 0;
        _rtmp312 = input.readMapBegin();
        _ktype9 = _rtmp312.ktype;
        _vtype10 = _rtmp312.vtype;
        _size8 = _rtmp312.size;
        for (var _i13 = 0; _i13 < _size8; ++_i13)
        {
          var key14 = null;
          var val15 = null;
          key14 = input.readString();
          val15 = input.readString();
          this.success[key14] = val15;
        }
        input.readMapEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

fontSubsetter.SubsetterService_getFontInfo_result.prototype.write = function(output) {
  output.writeStructBegin('SubsetterService_getFontInfo_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.MAP, 0);
    output.writeMapBegin(Thrift.Type.STRING, Thrift.Type.STRING, Thrift.objectLength(this.success));
    for (var kiter16 in this.success)
    {
      if (this.success.hasOwnProperty(kiter16))
      {
        var viter17 = this.success[kiter16];
        output.writeString(kiter16);
        output.writeString(viter17);
      }
    }
    output.writeMapEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

fontSubsetter.SubsetterServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this.seqid = 0;
    this._reqs = {};
};
fontSubsetter.SubsetterServiceClient.prototype = {};
fontSubsetter.SubsetterServiceClient.prototype.genSubset = function(filePath, outputDir, subset, types, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_genSubset(filePath, outputDir, subset, types);
};

fontSubsetter.SubsetterServiceClient.prototype.send_genSubset = function(filePath, outputDir, subset, types) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('genSubset', Thrift.MessageType.CALL, this.seqid);
  var args = new fontSubsetter.SubsetterService_genSubset_args();
  args.filePath = filePath;
  args.outputDir = outputDir;
  args.subset = subset;
  args.types = types;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

fontSubsetter.SubsetterServiceClient.prototype.recv_genSubset = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new fontSubsetter.SubsetterService_genSubset_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.ex) {
    return callback(result.ex);
  }
  callback(null)
};
fontSubsetter.SubsetterServiceClient.prototype.getFontInfo = function(filePath, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_getFontInfo(filePath);
};

fontSubsetter.SubsetterServiceClient.prototype.send_getFontInfo = function(filePath) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getFontInfo', Thrift.MessageType.CALL, this.seqid);
  var args = new fontSubsetter.SubsetterService_getFontInfo_args();
  args.filePath = filePath;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

fontSubsetter.SubsetterServiceClient.prototype.recv_getFontInfo = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new fontSubsetter.SubsetterService_getFontInfo_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getFontInfo failed: unknown result');
};
fontSubsetter.SubsetterServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
fontSubsetter.SubsetterServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.Exception, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

fontSubsetter.SubsetterServiceProcessor.prototype.process_genSubset = function(seqid, input, output) {
  var args = new fontSubsetter.SubsetterService_genSubset_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.genSubset(args.filePath, args.outputDir, args.subset, args.types, function (err, result) {
    var result = new fontSubsetter.SubsetterService_genSubset_result((err != null ? err : {success: result}));
    output.writeMessageBegin("genSubset", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

fontSubsetter.SubsetterServiceProcessor.prototype.process_getFontInfo = function(seqid, input, output) {
  var args = new fontSubsetter.SubsetterService_getFontInfo_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.getFontInfo(args.filePath, function (err, result) {
    var result = new fontSubsetter.SubsetterService_getFontInfo_result((err != null ? err : {success: result}));
    output.writeMessageBegin("getFontInfo", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

