//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


//HELPER FUNCTIONS AND STRUCTURES

fontSubsetter.SubsetterService_genSubset_args = function(args) {
  this.filePath = null;
  this.outputDir = null;
  this.subset = null;
  this.types = null;
  if (args) {
    if (args.filePath !== undefined) {
      this.filePath = args.filePath;
    }
    if (args.outputDir !== undefined) {
      this.outputDir = args.outputDir;
    }
    if (args.subset !== undefined) {
      this.subset = args.subset;
    }
    if (args.types !== undefined) {
      this.types = args.types;
    }
  }
};
fontSubsetter.SubsetterService_genSubset_args.prototype = {};
fontSubsetter.SubsetterService_genSubset_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.filePath = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.outputDir = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.subset = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.LIST) {
        var _size0 = 0;
        var _rtmp34;
        this.types = [];
        var _etype3 = 0;
        _rtmp34 = input.readListBegin();
        _etype3 = _rtmp34.etype;
        _size0 = _rtmp34.size;
        for (var _i5 = 0; _i5 < _size0; ++_i5)
        {
          var elem6 = null;
          elem6 = input.readI32().value;
          this.types.push(elem6);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

fontSubsetter.SubsetterService_genSubset_args.prototype.write = function(output) {
  output.writeStructBegin('SubsetterService_genSubset_args');
  if (this.filePath !== null && this.filePath !== undefined) {
    output.writeFieldBegin('filePath', Thrift.Type.STRING, 1);
    output.writeString(this.filePath);
    output.writeFieldEnd();
  }
  if (this.outputDir !== null && this.outputDir !== undefined) {
    output.writeFieldBegin('outputDir', Thrift.Type.STRING, 2);
    output.writeString(this.outputDir);
    output.writeFieldEnd();
  }
  if (this.subset !== null && this.subset !== undefined) {
    output.writeFieldBegin('subset', Thrift.Type.STRING, 3);
    output.writeString(this.subset);
    output.writeFieldEnd();
  }
  if (this.types !== null && this.types !== undefined) {
    output.writeFieldBegin('types', Thrift.Type.LIST, 4);
    output.writeListBegin(Thrift.Type.I32, this.types.length);
    for (var iter7 in this.types)
    {
      if (this.types.hasOwnProperty(iter7))
      {
        iter7 = this.types[iter7];
        output.writeI32(iter7);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

fontSubsetter.SubsetterService_genSubset_result = function(args) {
  this.ex = null;
  if (args instanceof fontSubsetter.IOException) {
    this.ex = args;
    return;
  }
  if (args) {
    if (args.ex !== undefined) {
      this.ex = args.ex;
    }
  }
};
fontSubsetter.SubsetterService_genSubset_result.prototype = {};
fontSubsetter.SubsetterService_genSubset_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.ex = new fontSubsetter.IOException();
        this.ex.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

fontSubsetter.SubsetterService_genSubset_result.prototype.write = function(output) {
  output.writeStructBegin('SubsetterService_genSubset_result');
  if (this.ex !== null && this.ex !== undefined) {
    output.writeFieldBegin('ex', Thrift.Type.STRUCT, 1);
    this.ex.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

fontSubsetter.SubsetterServiceClient = function(input, output) {
    this.input = input;
    this.output = (!output) ? input : output;
    this.seqid = 0;
};
fontSubsetter.SubsetterServiceClient.prototype = {};
fontSubsetter.SubsetterServiceClient.prototype.genSubset = function(filePath, outputDir, subset, types) {
  this.send_genSubset(filePath, outputDir, subset, types);
  this.recv_genSubset();
};

fontSubsetter.SubsetterServiceClient.prototype.send_genSubset = function(filePath, outputDir, subset, types) {
  this.output.writeMessageBegin('genSubset', Thrift.MessageType.CALL, this.seqid);
  var args = new fontSubsetter.SubsetterService_genSubset_args();
  args.filePath = filePath;
  args.outputDir = outputDir;
  args.subset = subset;
  args.types = types;
  args.write(this.output);
  this.output.writeMessageEnd();
  return this.output.getTransport().flush();
};

fontSubsetter.SubsetterServiceClient.prototype.recv_genSubset = function() {
  var ret = this.input.readMessageBegin();
  var fname = ret.fname;
  var mtype = ret.mtype;
  var rseqid = ret.rseqid;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new fontSubsetter.SubsetterService_genSubset_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.ex) {
    throw result.ex;
  }
  return;
};
